### ISSUE TITLE
TollRoll : Create Basic Index Html File for Home Page

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/TollRoll#1]
### Description

Welcome to 'TollRoll', good to see you here.

With this issue, the readers will get to know on how to create and implement a basic index file

To get assigned to this issue, add your participant id mentioned in this [spreadsheet](https://docs.google.com/spreadsheets/d/1SX9FubA-n1ag_0n4WmzMXd6rq5lrkFmaAWl8fhHvTWM/edit#gid=0) and the approach you would follow.

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title" should be the same. Include issue number in PR template along with it.

- You should add up in respective folder according to the demands of the issue.

- Inclusion of Screenshot and Video of the Outlook of the changes is must to approve 

This issue is only for 'SWOC' contributors

### Domain

Web Development

### Code of Conduct

- [X] I  will follow [Contributing Guidelines](https://github.com/prathimacode-hub/TollRoll/blob/main/CONTRIBUTING.md) & [Code of conduct](https://github.com/prathimacode-hub/TollRoll/blob/main/CODE_OF_CONDUCT.md) of this project.

All the best. Enjoy your open source journey ahead. 😎

**Comment by harikishantk** [comment]
I would like to work on, could you assign `level` label and assign me up

**Comment by prathimacode-hub** [comment]
Are you a SWOC participant? @harikishantk

**Comment by harikishantk** [comment]
Yes I am

**Comment by prathimacode-hub** [comment]
Issue assigned to @harikishantk. Label will be assigned to the PR. You can proceed. @harikishantk

**Comment by harikishantk** [comment]
So my task is create Django project and routing to the index.html, right?

**Comment by prathimacode-hub** [comment]
Basically for now you can only create index.html file since this is a beginner issue and later issues might come up soon @harikishantk

**Comment by harikishantk** [comment]
Yeah I mean according to the tech stacks in readme.md file, it has been mentioned Django. So that means Django project with index.html file right? 
@prathimacode-hub

**Comment by prathimacode-hub** [comment]
yes @harikishantk

**Comment by harikishantk** [comment]
@prathimacode-hub  Issue is fixed and raised PR. What I did:
- Established django project named "TollRoll"
- Created app called "home"
- Created index.html and routed it as main page

**Comment by harikishantk** [comment]
My Participant Id is 1187.
